spring.datasource.url=jdbc:postgresql://localhost:5432/fuel_station
spring.datasource.username=postgres
spring.datasource.password=Osman200202

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.redis.host=localhost
spring.data.redis.port=6379
