spring.datasource.url=jdbc:postgresql://localhost:5432/fuel_station
spring.datasource.username=postgres
spring.datasource.password=Osman200202

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true